/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Travis' at '10/20/16 4:31 PM' with Gradle 2.14.1
 *
 * @author Travis, @date 10/20/16 4:31 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
